services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data    
    environment:
      MINIO_ROOT_USER: developer
      MINIO_ROOT_PASSWORD: developer01
    command: server /data --console-address ":9001"

  
  jupyter:
    container_name: workspace
    build: ./images/workspace # Imagem configurada de jupyter/pyspark-notebook    
    ports: 
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work # Para mapear notebooks para pasta local
    